### PR TITLE
Set correct path for man-pages

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/ustreamer-debian/issues/3
Dependent on https://github.com/tiny-pilot/ustreamer-debian/pull/8

After installing our uStreamer Debian package, the man-pages didn't work:
```bash
$ man ustreamer
No manual entry for ustreamer
```

This is because the uStreamer's man-pages were being copied to `/opt/ustreamer` instead of `/usr/share/man`.

I've tested this on device.

### CODE REVIEW

**Comment by jdeanwallace** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/9)

⏳ @mtlynch please review this Pull Request

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/9)


<a href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/9">Approved on CodeApprove</a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by jdeanwallace** [comment]
@mtlynch - Thanks! Could you cut another uStreamer Debian release for us please?

**Comment by mtlynch** [comment]
@jdeanwallace - Sure, done:

https://github.com/tiny-pilot/ustreamer-debian/releases/tag/ustreamer_5.38-20230525134432

**Pull request merged**
