### PR TITLE
Build Debian package using ARM executor

### LINKED ISSUE #17: Build Debian package using ARM executor
We should be able to speed up this build a lot by using ARM machines on CircleCI.

We did something similar in TinyPilot:

https://github.com/tiny-pilot/tinypilot/pull/1588

We should keep instructions for building on AMD64 for development.

This might be a good opportunity to try [Exploding Servers](https://es.tinypilotkvm.com) during development, though we wouldn't add CI stuff that depends on Exploding Servers.

### PR DESCRIPTION
**Pull request by db39**
Resolves #17

This change switches the `build_debian_package` CircleCI step to use an ARM executor to speed up the build. The change also removes amd64 builds.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/22">Review on CodeApprove</a>

### CODE REVIEW

**Comment by db39** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/22)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/22)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM!

<hr />

In: **Discussion**
Can we also update our [`CONTRIBUTING` docs](https://github.com/tiny-pilot/tinypilot/blob/master/CONTRIBUTING.md?plain=1#L198) to no longer say that we build for both architectures?
> CircleCI builds the uStreamer Debian package for both `amd64`- and `armhf`-based architectures on every commit to the [`ustreamer-debian` repo](https://github.com/tiny-pilot/ustreamer-debian), which is stored as a CircleCI artifact.


<hr />

In: **Discussion**
Can we remove the `dev-scripts/enable-multiarch-docker` script?


<hr />

👀 @db39 it's your turn please take a look

**Review by db39 — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/22)



<hr />

In: **Discussion**
Resolved

<hr />

In: **Discussion**
I've created a [new issue/PR in the TinyPilot repository](https://github.com/tiny-pilot/tinypilot/pull/1798) for this.

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/22)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
