### PR TITLE
Add basic CircleCI config

### PR DESCRIPTION
**Pull request by jdeanwallace**
Related https://github.com/tiny-pilot/ustreamer-debian/issues/3

To eventually build a uStreamer Debian package in CI, we first need basic CI config.

This PR copies the following scripts from the TinyPilot Community repo and executes them as CircleCI jobs:
* [`dev-scripts/check-bash`](https://github.com/tiny-pilot/tinypilot/blob/d4273b9fe6f1faa7539467ba4d4054f50b99eb8f/dev-scripts/check-bash)
* [`dev-scripts/check-trailing-newline`](https://github.com/tiny-pilot/tinypilot/blob/d4273b9fe6f1faa7539467ba4d4054f50b99eb8f/dev-scripts/check-trailing-newline)
* [`dev-scripts/check-trailing-whitespace`](https://github.com/tiny-pilot/tinypilot/blob/d4273b9fe6f1faa7539467ba4d4054f50b99eb8f/dev-scripts/check-trailing-whitespace)

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/5">Review on CodeApprove</a>

### CODE REVIEW

**Comment by jdeanwallace** [comment]
@mtlynch - can you enable CircleCI for this repo please? [link](https://app.circleci.com/projects/project-dashboard/github/tiny-pilot/)

**Comment by mtlynch** [comment]
@jdeanwallace - Enabled!

**Comment by mtlynch** [comment]
@jotaen4tinypilot - Oh, yeah. I've just enabled it. I tried forcing it to create the review sticker in the PR description, but it doesn't seem to want to, but hopefully it works on future reviews

https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/5

**Comment by mtlynch** [comment]
@jotaen4tinypilot - Oh, yeah, showing up for me too now.

**Pull request merged**
