### PR TITLE
Build uStreamer Debian package with Janus plugin

### PR DESCRIPTION
**Pull request by jdeanwallace**
Resolves https://github.com/tiny-pilot/ustreamer-debian/issues/3

This PR builds a uStreamer Debian package (with Janus plugin) in CI. The reason why we couldn't just use the [official(?) uStreamer Debian package](https://salsa.debian.org/reedy/ustreamer/) is because it doesn't compile the Janus plugin (which we need for WebRTC support). 

Now we can avoid building uStreamer from source every time TinyPilot is installed or updated.

You can test the uStreamer Debian package on a device via this [scratch TinyPilot Pro build bundle](https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot-pro/2801/workflows/ba68bf47-f01c-4240-a008-6456f956dca4/jobs/20659/artifacts). 

Notes:

* We compile the uStreamer Debian package for both [`armhf` and `amd64` architectures](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R33-R38) because the `amd64` version will be used when testing the uStreamer Ansible role in CI (using molecule) and the `armhf` version will be used when installing TinyPilot on a device.

* FYI, compiling for multiple architectures produces Debian packages in the following [directory structure](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R46-R49):
  * `/build/linux_arm_v7/*.deb`
  * `/build/linux_amd64/*.deb`
  
  As opposed to just `/build/*.deb` when compiling for a single architecture.

* Most of the [lintian code](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R52-R80) is copy/pasted from [TinyPilot Community repo](https://github.com/tiny-pilot/tinypilot/blob/b984ab93a58533220ad6358831ce8e405810db8f/.circleci/continue_config.yml#L97-L122), besides the [loop to check multiple Debian packages](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R71-R80).

* Seeing as [uStreamer makes use of a simple `v${MAJOR}.${MINOR}` versioning schema](https://github.com/tiny-pilot/ustreamer/tags), I used that (without the `v` prefix) as the Debian package version with an added a timestamp revision number to allow for the Debian package to be updated even when the uStreamer version has stayed the same. The resulting uStreamer Debian package versioning schema being [`MAJOR.MINOR-YYYYMMDDhhmmss`](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R63)

* Seeing as Docker doesn't support dynamic `WORKDIR` values based on a command's output, I stole these ([1](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R46-R70), [2](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R140-R146)) clever workarounds from Michael's [PR](https://github.com/tiny-pilot/tinypilot/pull/1352/files#diff-d3aed37eb2a4156ced425c7bcab79741d1234d58d182d91099b780c3c3136ce4R31-R53).

* The [copyright notice I've used here](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-eb1289be1c2cdfc905cecdba0c6810aa4d987d52e34f9dee681c1ff9cd69c34fR1-R2) was given to me my Michael via email

* When we built uStreamer on the device, we technically [only ever ran `make`](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/b1017f8f4436071b5d8dcf812ee351fc846e1fa6/tasks/main.yml#L153-L161) and never `make install`. This Debian package builds using `make && make install` which results in the binary being moved to `bin/ustreamer`. I thought running the `make install` is a good thing, so I just [added a symlink (`/opt/ustreamer/ustreamer -> bin/ustreamer`)](https://github.com/tiny-pilot/ustreamer-debian/pull/6/files#diff-fe915a3611d3df024aa33709affc37ff7a049adc629d69f2f0fe0dd063ad155fR1-R2) to maintain TinyPilot's path to uStreamer.

Helpful resources on creating Debian packages:
* https://vincent.bernat.ch/en/blog/2019-pragmatic-debian-packaging
* https://github.com/vincentbernat/pragmatic-debian-packages/
* https://salsa.debian.org/reedy/ustreamer/
* https://github.com/tiny-pilot/tinypilot/pull/1352/files

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
We have another PR in progress that does ARMv7 + AMD64 builds in Docker+QEMU if it's helpful for reference:

https://github.com/tiny-pilot/tinypilot/pull/1352/files

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6)



Cool! Excited to see this coming through!



<hr />

In: **debian/ustreamer.copyright**:

```
> Line 2
Copyright (c) 2023 TinyPilot, LLC <legal@tinypilotkvm.com>
```
In addition to the copyright notice, we also need to include the GPLv3 license in the package:

https://github.com/tiny-pilot/ustreamer/blob/28c85991672b43b5a0e1c17329c000308293f5ba/LICENSE


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by mtlynch — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6)



<hr />

In: **Dockerfile**:

```
> Line 108
Homepage: https://pikvm.org/
```
That's true. Let's link to https://github.com/tiny-pilot/ustreamer


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

**Review by jdeanwallace — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6)



<hr />

In: **Discussion**
Yeah that would be one hell of a blog post/guide. This has been my 2nd attempt at building a Debian package ([this was my 1st](https://github.com/tiny-pilot/janus-gateway/pull/2)) and things were way easier this time, mostly thanks to [Michael's breakthrough on how to use `debhelper`](https://github.com/tiny-pilot/tinypilot/pull/1200) and [this blog post](https://vincent.bernat.ch/en/blog/2019-pragmatic-debian-packaging). So even though this time things went smoothly, I'm sure there's a lot more that I'm missing. That being a said, I would have wished for a quick start guide on `debhelper`, but I think that's mostly covered [here](https://vincent.bernat.ch/en/blog/2019-pragmatic-debian-packaging).

<hr />

In: **debian/ustreamer.copyright**:

```
> Line 2
Copyright (c) 2023 TinyPilot, LLC <legal@tinypilotkvm.com>
```
Done.

<hr />

In: **Dockerfile**:
It could be `ARG` too. I just went with `ENV` because I didn't think we'd need to change it. Should I be using `ARG` instead here?

<hr />

In: **Dockerfile**:
Done.

<hr />

In: **Dockerfile**:
Oh cool, I didn't know that, thanks. Removed.

<hr />

In: **Dockerfile**:
Oh nevermind, I just used `ARG` just incase.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6)


<a href="https://codeapprove.com/pr/tiny-pilot/ustreamer-debian/6">Approved on CodeApprove</a>
✔️ Approved

<hr />

👀 @jdeanwallace it's your turn please take a look

**Comment by mtlynch** [comment]
@jdeanwallace - Fixed, sorry! Raised it up with CodeApprove as well: https://github.com/codeapprove/feedback/issues/80#issuecomment-1561041070

**Pull request merged**
